name: Vite Github Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7

      - name: pnpm install deps
        run: pnpm install

      - name: pnpm run build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'

      - name: Create .nojekyll file
        run: |
          touch dist/.nojekyll
        shell: bash

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1